name: Trigger auto deployment for container-app-glbz5mn43mioc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-glbz5mn43mioc-AutoDeployTrigger-7ae2224c-046f-4ca1-b3d9-1ea00c3d0ba3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGLBZ5MN43MIOC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGLBZ5MN43MIOC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGLBZ5MN43MIOC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPGLBZ5MN43MIOC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGLBZ5MN43MIOC_REGISTRY_PASSWORD }}
          containerAppName: container-app-glbz5mn43mioc
          resourceGroup: todonodejspgsqlgoogleauth8cc1a108
          imageToBuild: default/container-app-glbz5mn43mioc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


